users:
 location: "/shoplifters"
 controller_name: "users_controller.rb"
 location: "/users/:id"
 controller_name: "users_controller.rb"

following:
  location: "/users/:user_id/following"
  controller_name: "following_controller.rb"

followers:
  location: "/users/:user_id/followers"
  controller_name: "followers_controller.rb"
  
timelines:
  controller_name: "timelines_controller.rb"

setasides:
  controller_name: "set_asides_controller.rb"