development:
  adapter: mysql2
  encoding: utf8
  database: shoplift_app_dev
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  database: shoplift_app_test
  username: root
  password:
  socket: /tmp/mysql.sock